from sqlmodel import SQLModel, create_engine, Session, select
from models import Problem, UserAttempt
from typing import List

engine = create_engine("sqlite:///./database.db", echo=True)


def create_db_and_tables():
    SQLModel.metadata.create_all(engine)


def create_problems(problems: List[Problem]):
    with Session(engine) as session:
        for problem in problems:
            session.add(problem)
        session.commit()


def create_attempt(attempt: UserAttempt):
    with Session(engine) as session:
        session.add(attempt)
        session.commit()


def get_all_problems():
    with Session(engine) as session:
        statement = select(Problem)
        results = session.exec(statement)
        return results.all()


def get_all_attempts():
    with Session(engine) as session:
        statement = select(UserAttempt)
        results = session.exec(statement)
        return results.all()


def seed_database():
    problems_data = [
        Problem(
            leetcode_id=1,
            title="Two Sum",
            url="https://leetcode.com/problems/two-sum/",
            difficulty="Easy",
            neetcode_order=1,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=2,
            title="Add Two Numbers",
            url="https://leetcode.com/problems/add-two-numbers/",
            difficulty="Medium",
            neetcode_order=2,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=3,
            title="Longest Substring Without Repeating Characters",
            url="https://leetcode.com/problems/longest-substring-without-repeating-characters/",
            difficulty="Medium",
            neetcode_order=3,
            neetcode_category="Sliding Window",
        ),
        Problem(
            leetcode_id=4,
            title="Median of Two Sorted Arrays",
            url="https://leetcode.com/problems/median-of-two-sorted-arrays/",
            difficulty="Hard",
            neetcode_order=4,
            neetcode_category="Binary Search",
        ),
        Problem(
            leetcode_id=5,
            title="Longest Palindromic Substring",
            url="https://leetcode.com/problems/longest-palindromic-substring/",
            difficulty="Medium",
            neetcode_order=5,
            neetcode_category="String",
        ),
        Problem(
            leetcode_id=7,
            title="Reverse Integer",
            url="https://leetcode.com/problems/reverse-integer/",
            difficulty="Medium",
            neetcode_order=6,
            neetcode_category="Math",
        ),
        Problem(
            leetcode_id=11,
            title="Container With Most Water",
            url="https://leetcode.com/problems/container-with-most-water/",
            difficulty="Medium",
            neetcode_order=7,
            neetcode_category="Two Pointers",
        ),
        Problem(
            leetcode_id=15,
            title="3Sum",
            url="https://leetcode.com/problems/3sum/",
            difficulty="Medium",
            neetcode_order=8,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=17,
            title="Letter Combinations of a Phone Number",
            url="https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
            difficulty="Medium",
            neetcode_order=9,
            neetcode_category="Backtracking",
        ),
        Problem(
            leetcode_id=19,
            title="Remove Nth Node From End of List",
            url="https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
            difficulty="Medium",
            neetcode_order=10,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=20,
            title="Valid Parentheses",
            url="https://leetcode.com/problems/valid-parentheses/",
            difficulty="Easy",
            neetcode_order=11,
            neetcode_category="Stack",
        ),
        Problem(
            leetcode_id=21,
            title="Merge Two Sorted Lists",
            url="https://leetcode.com/problems/merge-two-sorted-lists/",
            difficulty="Easy",
            neetcode_order=12,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=22,
            title="Generate Parentheses",
            url="https://leetcode.com/problems/generate-parentheses/",
            difficulty="Medium",
            neetcode_order=13,
            neetcode_category="Backtracking",
        ),
        Problem(
            leetcode_id=23,
            title="Merge k Sorted Lists",
            url="https://leetcode.com/problems/merge-k-sorted-lists/",
            difficulty="Hard",
            neetcode_order=14,
            neetcode_category="Heap / Priority Queue",
        ),
        Problem(
            leetcode_id=26,
            title="Remove Duplicates from Sorted Array",
            url="https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
            difficulty="Easy",
            neetcode_order=15,
            neetcode_category="Two Pointers",
        ),
        Problem(
            leetcode_id=33,
            title="Search in Rotated Sorted Array",
            url="https://leetcode.com/problems/search-in-rotated-sorted-array/",
            difficulty="Medium",
            neetcode_order=16,
            neetcode_category="Binary Search",
        ),
        Problem(
            leetcode_id=39,
            title="Combination Sum",
            url="https://leetcode.com/problems/combination-sum/",
            difficulty="Medium",
            neetcode_order=17,
            neetcode_category="Backtracking",
        ),
        Problem(
            leetcode_id=42,
            title="Trapping Rain Water",
            url="https://leetcode.com/problems/trapping-rain-water/",
            difficulty="Hard",
            neetcode_order=18,
            neetcode_category="Two Pointers",
        ),
        Problem(
            leetcode_id=46,
            title="Permutations",
            url="https://leetcode.com/problems/permutations/",
            difficulty="Medium",
            neetcode_order=19,
            neetcode_category="Backtracking",
        ),
        Problem(
            leetcode_id=48,
            title="Rotate Image",
            url="https://leetcode.com/problems/rotate-image/",
            difficulty="Medium",
            neetcode_order=20,
            neetcode_category="Matrix",
        ),
        Problem(
            leetcode_id=49,
            title="Group Anagrams",
            url="https://leetcode.com/problems/group-anagrams/",
            difficulty="Medium",
            neetcode_order=21,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=53,
            title="Maximum Subarray",
            url="https://leetcode.com/problems/maximum-subarray/",
            difficulty="Medium",
            neetcode_order=22,
            neetcode_category="Divide and Conquer",
        ),
        Problem(
            leetcode_id=55,
            title="Jump Game",
            url="https://leetcode.com/problems/jump-game/",
            difficulty="Medium",
            neetcode_order=23,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=56,
            title="Merge Intervals",
            url="https://leetcode.com/problems/merge-intervals/",
            difficulty="Medium",
            neetcode_order=24,
            neetcode_category="Intervals",
        ),
        Problem(
            leetcode_id=57,
            title="Insert Interval",
            url="https://leetcode.com/problems/insert-interval/",
            difficulty="Medium",
            neetcode_order=25,
            neetcode_category="Intervals",
        ),
        Problem(
            leetcode_id=62,
            title="Unique Paths",
            url="https://leetcode.com/problems/unique-paths/",
            difficulty="Medium",
            neetcode_order=26,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=64,
            title="Minimum Path Sum",
            url="https://leetcode.com/problems/minimum-path-sum/",
            difficulty="Medium",
            neetcode_order=27,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=70,
            title="Climbing Stairs",
            url="https://leetcode.com/problems/climbing-stairs/",
            difficulty="Easy",
            neetcode_order=28,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=72,
            title="Edit Distance",
            url="https://leetcode.com/problems/edit-distance/",
            difficulty="Medium",
            neetcode_order=29,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=73,
            title="Set Matrix Zeroes",
            url="https://leetcode.com/problems/set-matrix-zeroes/",
            difficulty="Medium",
            neetcode_order=30,
            neetcode_category="Matrix",
        ),
        Problem(
            leetcode_id=75,
            title="Sort Colors",
            url="https://leetcode.com/problems/sort-colors/",
            difficulty="Medium",
            neetcode_order=31,
            neetcode_category="Two Pointers",
        ),
        Problem(
            leetcode_id=76,
            title="Minimum Window Substring",
            url="https://leetcode.com/problems/minimum-window-substring/",
            difficulty="Hard",
            neetcode_order=32,
            neetcode_category="Sliding Window",
        ),
        Problem(
            leetcode_id=78,
            title="Subsets",
            url="https://leetcode.com/problems/subsets/",
            difficulty="Medium",
            neetcode_order=33,
            neetcode_category="Backtracking",
        ),
        Problem(
            leetcode_id=79,
            title="Word Search",
            url="https://leetcode.com/problems/word-search/",
            difficulty="Medium",
            neetcode_order=34,
            neetcode_category="Backtracking",
        ),
        Problem(
            leetcode_id=84,
            title="Largest Rectangle in Histogram",
            url="https://leetcode.com/problems/largest-rectangle-in-histogram/",
            difficulty="Hard",
            neetcode_order=35,
            neetcode_category="Stack",
        ),
        Problem(
            leetcode_id=85,
            title="Maximal Rectangle",
            url="https://leetcode.com/problems/maximal-rectangle/",
            difficulty="Hard",
            neetcode_order=36,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=91,
            title="Decode Ways",
            url="https://leetcode.com/problems/decode-ways/",
            difficulty="Medium",
            neetcode_order=37,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=94,
            title="Binary Tree Inorder Traversal",
            url="https://leetcode.com/problems/binary-tree-inorder-traversal/",
            difficulty="Easy",
            neetcode_order=38,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=96,
            title="Unique Binary Search Trees",
            url="https://leetcode.com/problems/unique-binary-search-trees/",
            difficulty="Medium",
            neetcode_order=39,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=98,
            title="Validate Binary Search Tree",
            url="https://leetcode.com/problems/validate-binary-search-tree/",
            difficulty="Medium",
            neetcode_order=40,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=100,
            title="Same Tree",
            url="https://leetcode.com/problems/same-tree/",
            difficulty="Easy",
            neetcode_order=41,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=101,
            title="Symmetric Tree",
            url="https://leetcode.com/problems/symmetric-tree/",
            difficulty="Easy",
            neetcode_order=42,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=102,
            title="Binary Tree Level Order Traversal",
            url="https://leetcode.com/problems/binary-tree-level-order-traversal/",
            difficulty="Medium",
            neetcode_order=43,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=104,
            title="Maximum Depth of Binary Tree",
            url="https://leetcode.com/problems/maximum-depth-of-binary-tree/",
            difficulty="Easy",
            neetcode_order=44,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=105,
            title="Construct Binary Tree from Preorder and Inorder Traversal",
            url="https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
            difficulty="Medium",
            neetcode_order=45,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=108,
            title="Convert Sorted Array to Binary Search Tree",
            url="https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/",
            difficulty="Easy",
            neetcode_order=46,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=110,
            title="Balanced Binary Tree",
            url="https://leetcode.com/problems/balanced-binary-tree/",
            difficulty="Easy",
            neetcode_order=47,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=112,
            title="Path Sum",
            url="https://leetcode.com/problems/path-sum/",
            difficulty="Easy",
            neetcode_order=48,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=113,
            title="Path Sum II",
            url="https://leetcode.com/problems/path-sum-ii/",
            difficulty="Medium",
            neetcode_order=49,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=114,
            title="Flatten Binary Tree to Linked List",
            url="https://leetcode.com/problems/flatten-binary-tree-to-linked-list/",
            difficulty="Medium",
            neetcode_order=50,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=121,
            title="Best Time to Buy and Sell Stock",
            url="https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
            difficulty="Easy",
            neetcode_order=51,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=124,
            title="Binary Tree Maximum Path Sum",
            url="https://leetcode.com/problems/binary-tree-maximum-path-sum/",
            difficulty="Hard",
            neetcode_order=52,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=128,
            title="Longest Consecutive Sequence",
            url="https://leetcode.com/problems/longest-consecutive-sequence/",
            difficulty="Medium",
            neetcode_order=53,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=130,
            title="Surrounded Regions",
            url="https://leetcode.com/problems/surrounded-regions/",
            difficulty="Medium",
            neetcode_order=54,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=131,
            title="Palindrome Partitioning",
            url="https://leetcode.com/problems/palindrome-partitioning/",
            difficulty="Medium",
            neetcode_order=55,
            neetcode_category="Backtracking",
        ),
        Problem(
            leetcode_id=133,
            title="Clone Graph",
            url="https://leetcode.com/problems/clone-graph/",
            difficulty="Medium",
            neetcode_order=56,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=134,
            title="Gas Station",
            url="https://leetcode.com/problems/gas-station/",
            difficulty="Medium",
            neetcode_order=57,
            neetcode_category="Greedy",
        ),
        Problem(
            leetcode_id=136,
            title="Single Number",
            url="https://leetcode.com/problems/single-number/",
            difficulty="Easy",
            neetcode_order=58,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=139,
            title="Word Break",
            url="https://leetcode.com/problems/word-break/",
            difficulty="Medium",
            neetcode_order=59,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=141,
            title="Linked List Cycle",
            url="https://leetcode.com/problems/linked-list-cycle/",
            difficulty="Easy",
            neetcode_order=60,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=142,
            title="Linked List Cycle II",
            url="https://leetcode.com/problems/linked-list-cycle-ii/",
            difficulty="Medium",
            neetcode_order=61,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=143,
            title="Reorder List",
            url="https://leetcode.com/problems/reorder-list/",
            difficulty="Medium",
            neetcode_order=62,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=146,
            title="LRU Cache",
            url="https://leetcode.com/problems/lru-cache/",
            difficulty="Medium",
            neetcode_order=63,
            neetcode_category="Hash Map / Linked List",
        ),
        Problem(
            leetcode_id=148,
            title="Sort List",
            url="https://leetcode.com/problems/sort-list/",
            difficulty="Medium",
            neetcode_order=64,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=150,
            title="Evaluate Reverse Polish Notation",
            url="https://leetcode.com/problems/evaluate-reverse-polish-notation/",
            difficulty="Medium",
            neetcode_order=65,
            neetcode_category="Stack",
        ),
        Problem(
            leetcode_id=152,
            title="Maximum Product Subarray",
            url="https://leetcode.com/problems/maximum-product-subarray/",
            difficulty="Medium",
            neetcode_order=66,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=153,
            title="Find Minimum in Rotated Sorted Array",
            url="https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
            difficulty="Medium",
            neetcode_order=67,
            neetcode_category="Binary Search",
        ),
        Problem(
            leetcode_id=155,
            title="Min Stack",
            url="https://leetcode.com/problems/min-stack/",
            difficulty="Easy",
            neetcode_order=68,
            neetcode_category="Stack",
        ),
        Problem(
            leetcode_id=160,
            title="Intersection of Two Linked Lists",
            url="https://leetcode.com/problems/intersection-of-two-linked-lists/",
            difficulty="Easy",
            neetcode_order=69,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=167,
            title="Two Sum II - Input Array Is Sorted",
            url="https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
            difficulty="Medium",
            neetcode_order=70,
            neetcode_category="Two Pointers",
        ),
        Problem(
            leetcode_id=169,
            title="Majority Element",
            url="https://leetcode.com/problems/majority-element/",
            difficulty="Easy",
            neetcode_order=71,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=190,
            title="Reverse Bits",
            url="https://leetcode.com/problems/reverse-bits/",
            difficulty="Easy",
            neetcode_order=72,
            neetcode_category="Bit Manipulation",
        ),
        Problem(
            leetcode_id=191,
            title="Number of 1 Bits",
            url="https://leetcode.com/problems/number-of-1-bits/",
            difficulty="Easy",
            neetcode_order=73,
            neetcode_category="Bit Manipulation",
        ),
        Problem(
            leetcode_id=198,
            title="House Robber",
            url="https://leetcode.com/problems/house-robber/",
            difficulty="Medium",
            neetcode_order=74,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=200,
            title="Number of Islands",
            url="https://leetcode.com/problems/number-of-islands/",
            difficulty="Medium",
            neetcode_order=75,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=206,
            title="Reverse Linked List",
            url="https://leetcode.com/problems/reverse-linked-list/",
            difficulty="Easy",
            neetcode_order=76,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=207,
            title="Course Schedule",
            url="https://leetcode.com/problems/course-schedule/",
            difficulty="Medium",
            neetcode_order=77,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=208,
            title="Implement Trie (Prefix Tree)",
            url="https://leetcode.com/problems/implement-trie-prefix-tree/",
            difficulty="Medium",
            neetcode_order=78,
            neetcode_category="Trie",
        ),
        Problem(
            leetcode_id=210,
            title="Course Schedule II",
            url="https://leetcode.com/problems/course-schedule-ii/",
            difficulty="Medium",
            neetcode_order=79,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=212,
            title="Word Search II",
            url="https://leetcode.com/problems/word-search-ii/",
            difficulty="Hard",
            neetcode_order=80,
            neetcode_category="Trie",
        ),
        Problem(
            leetcode_id=215,
            title="Kth Largest Element in an Array",
            url="https://leetcode.com/problems/kth-largest-element-in-an-array/",
            difficulty="Medium",
            neetcode_order=81,
            neetcode_category="Heap / Priority Queue",
        ),
        Problem(
            leetcode_id=217,
            title="Contains Duplicate",
            url="https://leetcode.com/problems/contains-duplicate/",
            difficulty="Easy",
            neetcode_order=82,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=226,
            title="Invert Binary Tree",
            url="https://leetcode.com/problems/invert-binary-tree/",
            difficulty="Easy",
            neetcode_order=83,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=230,
            title="Kth Smallest Element in a BST",
            url="https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
            difficulty="Medium",
            neetcode_order=84,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=234,
            title="Palindrome Linked List",
            url="https://leetcode.com/problems/palindrome-linked-list/",
            difficulty="Easy",
            neetcode_order=85,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=235,
            title="Lowest Common Ancestor of a Binary Search Tree",
            url="https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
            difficulty="Easy",
            neetcode_order=86,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=236,
            title="Lowest Common Ancestor of a Binary Tree",
            url="https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
            difficulty="Medium",
            neetcode_order=87,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=238,
            title="Product of Array Except Self",
            url="https://leetcode.com/problems/product-of-array-except-self/",
            difficulty="Medium",
            neetcode_order=88,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=239,
            title="Sliding Window Maximum",
            url="https://leetcode.com/problems/sliding-window-maximum/",
            difficulty="Hard",
            neetcode_order=89,
            neetcode_category="Sliding Window",
        ),
        Problem(
            leetcode_id=240,
            title="Search a 2D Matrix II",
            url="https://leetcode.com/problems/search-a-2d-matrix-ii/",
            difficulty="Medium",
            neetcode_order=90,
            neetcode_category="Binary Search",
        ),
        Problem(
            leetcode_id=242,
            title="Valid Anagram",
            url="https://leetcode.com/problems/valid-anagram/",
            difficulty="Easy",
            neetcode_order=91,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=252,
            title="Meeting Rooms",
            url="https://leetcode.com/problems/meeting-rooms/",
            difficulty="Easy",
            neetcode_order=92,
            neetcode_category="Intervals",
        ),
        Problem(
            leetcode_id=253,
            title="Meeting Rooms II",
            url="https://leetcode.com/problems/meeting-rooms-ii/",
            difficulty="Medium",
            neetcode_order=93,
            neetcode_category="Intervals",
        ),
        Problem(
            leetcode_id=268,
            title="Missing Number",
            url="https://leetcode.com/problems/missing-number/",
            difficulty="Easy",
            neetcode_order=94,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=269,
            title="Alien Dictionary",
            url="https://leetcode.com/problems/alien-dictionary/",
            difficulty="Hard",
            neetcode_order=95,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=278,
            title="First Bad Version",
            url="https://leetcode.com/problems/first-bad-version/",
            difficulty="Easy",
            neetcode_order=96,
            neetcode_category="Binary Search",
        ),
        Problem(
            leetcode_id=283,
            title="Move Zeroes",
            url="https://leetcode.com/problems/move-zeroes/",
            difficulty="Easy",
            neetcode_order=97,
            neetcode_category="Two Pointers",
        ),
        Problem(
            leetcode_id=287,
            title="Find the Duplicate Number",
            url="https://leetcode.com/problems/find-the-duplicate-number/",
            difficulty="Medium",
            neetcode_order=98,
            neetcode_category="Two Pointers",
        ),
        Problem(
            leetcode_id=297,
            title="Serialize and Deserialize Binary Tree",
            url="https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
            difficulty="Hard",
            neetcode_order=99,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=300,
            title="Longest Increasing Subsequence",
            url="https://leetcode.com/problems/longest-increasing-subsequence/",
            difficulty="Medium",
            neetcode_order=100,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=309,
            title="Best Time to Buy and Sell Stock with Cooldown",
            url="https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/",
            difficulty="Medium",
            neetcode_order=101,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=322,
            title="Coin Change",
            url="https://leetcode.com/problems/coin-change/",
            difficulty="Medium",
            neetcode_order=102,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=328,
            title="Odd Even Linked List",
            url="https://leetcode.com/problems/odd-even-linked-list/",
            difficulty="Medium",
            neetcode_order=103,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=338,
            title="Counting Bits",
            url="https://leetcode.com/problems/counting-bits/",
            difficulty="Easy",
            neetcode_order=104,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=347,
            title="Top K Frequent Elements",
            url="https://leetcode.com/problems/top-k-frequent-elements/",
            difficulty="Medium",
            neetcode_order=105,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=371,
            title="Sum of Two Integers",
            url="https://leetcode.com/problems/sum-of-two-integers/",
            difficulty="Medium",
            neetcode_order=106,
            neetcode_category="Bit Manipulation",
        ),
        Problem(
            leetcode_id=394,
            title="Decode String",
            url="https://leetcode.com/problems/decode-string/",
            difficulty="Medium",
            neetcode_order=107,
            neetcode_category="Stack",
        ),
        Problem(
            leetcode_id=416,
            title="Partition Equal Subset Sum",
            url="https://leetcode.com/problems/partition-equal-subset-sum/",
            difficulty="Medium",
            neetcode_order=108,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=435,
            title="Non-overlapping Intervals",
            url="https://leetcode.com/problems/non-overlapping-intervals/",
            difficulty="Medium",
            neetcode_order=109,
            neetcode_category="Intervals",
        ),
        Problem(
            leetcode_id=437,
            title="Path Sum III",
            url="https://leetcode.com/problems/path-sum-iii/",
            difficulty="Medium",
            neetcode_order=110,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=438,
            title="Find All Anagrams in a String",
            url="https://leetcode.com/problems/find-all-anagrams-in-a-string/",
            difficulty="Medium",
            neetcode_order=111,
            neetcode_category="Sliding Window",
        ),
        Problem(
            leetcode_id=448,
            title="Find All Numbers Disappeared in an Array",
            url="https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/",
            difficulty="Easy",
            neetcode_order=112,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=494,
            title="Target Sum",
            url="https://leetcode.com/problems/target-sum/",
            difficulty="Medium",
            neetcode_order=113,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=543,
            title="Diameter of Binary Tree",
            url="https://leetcode.com/problems/diameter-of-binary-tree/",
            difficulty="Easy",
            neetcode_order=114,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=572,
            title="Subtree of Another Tree",
            url="https://leetcode.com/problems/subtree-of-another-tree/",
            difficulty="Easy",
            neetcode_order=115,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=581,
            title="Shortest Unsorted Continuous Subarray",
            url="https://leetcode.com/problems/shortest-unsorted-continuous-subarray/",
            difficulty="Medium",
            neetcode_order=116,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=621,
            title="Task Scheduler",
            url="https://leetcode.com/problems/task-scheduler/",
            difficulty="Medium",
            neetcode_order=117,
            neetcode_category="Heap / Priority Queue",
        ),
        Problem(
            leetcode_id=647,
            title="Palindromic Substrings",
            url="https://leetcode.com/problems/palindromic-substrings/",
            difficulty="Medium",
            neetcode_order=118,
            neetcode_category="Dynamic Programming",
        ),
        Problem(
            leetcode_id=678,
            title="Valid Parenthesis String",
            url="https://leetcode.com/problems/valid-parenthesis-string/",
            difficulty="Medium",
            neetcode_order=119,
            neetcode_category="String",
        ),
        Problem(
            leetcode_id=695,
            title="Max Area of Island",
            url="https://leetcode.com/problems/max-area-of-island/",
            difficulty="Medium",
            neetcode_order=120,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=703,
            title="Kth Largest Element in a Stream",
            url="https://leetcode.com/problems/kth-largest-element-in-a-stream/",
            difficulty="Easy",
            neetcode_order=121,
            neetcode_category="Heap / Priority Queue",
        ),
        Problem(
            leetcode_id=704,
            title="Binary Search",
            url="https://leetcode.com/problems/binary-search/",
            difficulty="Easy",
            neetcode_order=122,
            neetcode_category="Binary Search",
        ),
        Problem(
            leetcode_id=721,
            title="Accounts Merge",
            url="https://leetcode.com/problems/accounts-merge/",
            difficulty="Medium",
            neetcode_order=123,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=739,
            title="Daily Temperatures",
            url="https://leetcode.com/problems/daily-temperatures/",
            difficulty="Medium",
            neetcode_order=124,
            neetcode_category="Stack",
        ),
        Problem(
            leetcode_id=743,
            title="Network Delay Time",
            url="https://leetcode.com/problems/network-delay-time/",
            difficulty="Medium",
            neetcode_order=125,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=763,
            title="Partition Labels",
            url="https://leetcode.com/problems/partition-labels/",
            difficulty="Medium",
            neetcode_order=126,
            neetcode_category="Greedy",
        ),
        Problem(
            leetcode_id=787,
            title="Cheapest Flights Within K Stops",
            url="https://leetcode.com/problems/cheapest-flights-within-k-stops/",
            difficulty="Medium",
            neetcode_order=127,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=853,
            title="Car Fleet",
            url="https://leetcode.com/problems/car-fleet/",
            difficulty="Medium",
            neetcode_order=128,
            neetcode_category="Stack",
        ),
        Problem(
            leetcode_id=875,
            title="Koko Eating Bananas",
            url="https://leetcode.com/problems/koko-eating-bananas/",
            difficulty="Medium",
            neetcode_order=129,
            neetcode_category="Binary Search",
        ),
        Problem(
            leetcode_id=981,
            title="Time Based Key-Value Store",
            url="https://leetcode.com/problems/time-based-key-value-store/",
            difficulty="Medium",
            neetcode_order=130,
            neetcode_category="Hash Map",
        ),
        Problem(
            leetcode_id=1046,
            title="Last Stone Weight",
            url="https://leetcode.com/problems/last-stone-weight/",
            difficulty="Easy",
            neetcode_order=131,
            neetcode_category="Heap / Priority Queue",
        ),
        Problem(
            leetcode_id=1249,
            title="Minimum Remove to Make Valid Parentheses",
            url="https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/",
            difficulty="Medium",
            neetcode_order=132,
            neetcode_category="Stack",
        ),
        Problem(
            leetcode_id=1584,
            title="Min Cost to Connect All Points",
            url="https://leetcode.com/problems/min-cost-to-connect-all-points/",
            difficulty="Medium",
            neetcode_order=133,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=1834,
            title="Single-Threaded CPU",
            url="https://leetcode.com/problems/single-threaded-cpu/",
            difficulty="Medium",
            neetcode_order=134,
            neetcode_category="Heap / Priority Queue",
        ),
        Problem(
            leetcode_id=2101,
            title="Detonate the Maximum Bombs",
            url="https://leetcode.com/problems/detonate-the-maximum-bombs/",
            difficulty="Medium",
            neetcode_order=135,
            neetcode_category="Graph",
        ),
    ]
    with Session(engine) as session:
        statement = select(Problem)
        results = session.exec(statement)
        if results.first():
            print("DB already init")
            return
        for problem in problems_data:
            session.add(problem)
        session.commit()
