from sqlmodel import SQLModel, create_engine, Session, select
from models import Problem, UserAttempt, ProblemMemory  # ⬅️ added ProblemMemory
from typing import List, Optional
from sqlalchemy import desc

engine = create_engine("sqlite:///./database.db", echo=True)


def create_db_and_tables():
    SQLModel.metadata.create_all(engine)


def create_problems(problems: List[Problem]):
    with Session(engine) as session:
        for problem in problems:
            session.add(problem)
        session.commit()


def create_attempt(attempt: UserAttempt):
    with Session(engine) as session:
        session.add(attempt)
        session.commit()


def get_all_problems():
    with Session(engine) as session:
        statement = select(Problem)
        results = session.exec(statement)
        return results.all()


def get_all_attempts():
    with Session(engine) as session:
        statement = select(UserAttempt)
        results = session.exec(statement)
        return results.all()


def get_last_attempt(problem_id: int) -> Optional[UserAttempt]:
    with Session(engine) as session:
        statement = (
            select(UserAttempt)
            .where(UserAttempt.problem_id == problem_id)
            .order_by(desc(UserAttempt.attempt_date))
        )
        return session.exec(statement).first()


# ⬇️ NEW FUNCTION: Get or create ProblemMemory
def get_or_create_problem_memory(problem_id: int) -> ProblemMemory:
    with Session(engine) as session:
        statement = select(ProblemMemory).where(ProblemMemory.problem_id == problem_id)
        memory = session.exec(statement).first()

        if not memory:
            memory = ProblemMemory(problem_id=problem_id)
            session.add(memory)
            session.commit()
            session.refresh(memory)

        return memory


# ⬇️ NEW FUNCTION: Update ProblemMemory (after SM-2 scheduling)
def update_problem_memory(memory: ProblemMemory):
    with Session(engine) as session:
        session.add(memory)
        session.commit()


def seed_database():
    problems_data = [
        Problem(
            leetcode_id=217,
            title="Contains Duplicate",
            url="https://leetcode.com/problems/contains-duplicate/",
            difficulty="Easy",
            neetcode_order=1,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=242,
            title="Valid Anagram",
            url="https://leetcode.com/problems/valid-anagram/",
            difficulty="Easy",
            neetcode_order=2,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=1,
            title="Two Sum",
            url="https://leetcode.com/problems/two-sum/",
            difficulty="Easy",
            neetcode_order=3,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=49,
            title="Group Anagrams",
            url="https://leetcode.com/problems/group-anagrams/",
            difficulty="Medium",
            neetcode_order=4,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=347,
            title="Top K Frequent Elements",
            url="https://leetcode.com/problems/top-k-frequent-elements/",
            difficulty="Medium",
            neetcode_order=5,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=271,
            title="Encode and Decode Strings",
            url="https://neetcode.io/problems/string-encode-and-decode",
            difficulty="Medium",
            neetcode_order=6,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=238,
            title="Product of Array Except Self",
            url="https://leetcode.com/problems/product-of-array-except-self/",
            difficulty="Medium",
            neetcode_order=7,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=36,
            title="Valid Sudoku",
            url="https://leetcode.com/problems/valid-sudoku/",
            difficulty="Medium",
            neetcode_order=8,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=128,
            title="Longest Consecutive Sequence",
            url="https://leetcode.com/problems/longest-consecutive-sequence/",
            difficulty="Medium",
            neetcode_order=9,
            neetcode_category="Arrays and Hashing",
        ),
        Problem(
            leetcode_id=125,
            title="Valid Palindrome",
            url="https://leetcode.com/problems/valid-palindrome/",
            difficulty="Easy",
            neetcode_order=10,
            neetcode_category="Two Pointers",
        ),
        Problem(
            leetcode_id=167,
            title="Two Sum II - Input Array Is Sorted",
            url="https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
            difficulty="Medium",
            neetcode_order=11,
            neetcode_category="Two Pointers",
        ),
        Problem(
            leetcode_id=15,
            title="3Sum",
            url="https://leetcode.com/problems/3sum/",
            difficulty="Medium",
            neetcode_order=12,
            neetcode_category="Two Pointers",
        ),
        Problem(
            leetcode_id=11,
            title="Container With Most Water",
            url="https://leetcode.com/problems/container-with-most-water/",
            difficulty="Medium",
            neetcode_order=13,
            neetcode_category="Two Pointers",
        ),
        Problem(
            leetcode_id=42,
            title="Trapping Rain Water",
            url="https://leetcode.com/problems/trapping-rain-water/",
            difficulty="Hard",
            neetcode_order=14,
            neetcode_category="Two Pointers",
        ),
        Problem(
            leetcode_id=20,
            title="Valid Parentheses",
            url="https://leetcode.com/problems/valid-parentheses/",
            difficulty="Easy",
            neetcode_order=15,
            neetcode_category="Stack",
        ),
        Problem(
            leetcode_id=155,
            title="Min Stack",
            url="https://leetcode.com/problems/min-stack/",
            difficulty="Medium",
            neetcode_order=16,
            neetcode_category="Stack",
        ),
        Problem(
            leetcode_id=150,
            title="Evaluate Revserse Polish Notation",
            url="https://leetcode.com/problems/evaluate-reverse-polish-notation/",
            difficulty="Medium",
            neetcode_order=17,
            neetcode_category="Stack",
        ),
        Problem(
            leetcode_id=22,
            title="Generate Parenthesis",
            url="https://leetcode.com/problems/generate-parentheses/",
            difficulty="Medium",
            neetcode_order=18,
            neetcode_category="Stack",
        ),
        Problem(
            leetcode_id=739,
            title="Daily Temperatures",
            url="https://leetcode.com/problems/daily-temperatures/",
            difficulty="Medium",
            neetcode_order=19,
            neetcode_category="Stack",
        ),
        Problem(
            leetcode_id=853,
            title="Car Fleet",
            url="https://leetcode.com/problems/car-fleet/",
            difficulty="Medium",
            neetcode_order=20,
            neetcode_category="Stack",
        ),
        Problem(
            leetcode_id=84,
            title="Largest Rectangle in Histogram",
            url="https://leetcode.com/problems/largest-rectangle-in-histogram/",
            difficulty="Hard",
            neetcode_order=21,
            neetcode_category="Stack",
        ),
        Problem(
            leetcode_id=704,
            title="Binary Search",
            url="https://leetcode.com/problems/binary-search/",
            difficulty="Easy",
            neetcode_order=22,
            neetcode_category="Binary Search",
        ),
        Problem(
            leetcode_id=74,
            title="Search A 2D Matrix",
            url="https://leetcode.com/problems/search-a-2d-matrix/",
            difficulty="Medium",
            neetcode_order=23,
            neetcode_category="Binary Search",
        ),
        Problem(
            leetcode_id=875,
            title="Koko Eating Bananas",
            url="https://leetcode.com/problems/koko-eating-bananas/",
            difficulty="Medium",
            neetcode_order=24,
            neetcode_category="Binary Search",
        ),
        Problem(
            leetcode_id=153,
            title="Find Minimum In Rotated Sorted Array",
            url="https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
            difficulty="Medium",
            neetcode_order=25,
            neetcode_category="Binary Search",
        ),
        Problem(
            leetcode_id=33,
            title="Search in Rotated Sorted Array",
            url="https://leetcode.com/problems/search-in-rotated-sorted-array/",
            difficulty="Medium",
            neetcode_order=26,
            neetcode_category="Binary Search",
        ),
        Problem(
            leetcode_id=891,
            title="Time Based Key Value Store",
            url="https://leetcode.com/problems/time-based-key-value-store/",
            difficulty="Medium",
            neetcode_order=27,
            neetcode_category="Binary Search",
        ),
        Problem(
            leetcode_id=4,
            title="Median of Two Sorted Arrays",
            url="https://leetcode.com/problems/median-of-two-sorted-arrays/",
            difficulty="Hard",
            neetcode_order=28,
            neetcode_category="Binary Search",
        ),
        Problem(
            leetcode_id=121,
            title="Best Time To Buy and Sell Stock",
            url="https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
            difficulty="Easy",
            neetcode_order=29,
            neetcode_category="Sliding Window",
        ),
        Problem(
            leetcode_id=3,
            title="Longest Substring Without Repeating Characters",
            url="https://leetcode.com/problems/longest-substring-without-repeating-characters/",
            difficulty="Medium",
            neetcode_order=30,
            neetcode_category="Sliding Window",
        ),
        Problem(
            leetcode_id=424,
            title="Longest Repeating Character Replacement",
            url="https://leetcode.com/problems/longest-repeating-character-replacement/",
            difficulty="Medium",
            neetcode_order=31,
            neetcode_category="Sliding Window",
        ),
        Problem(
            leetcode_id=567,
            title="Permutation in String",
            url="https://leetcode.com/problems/permutation-in-string/",
            difficulty="Medium",
            neetcode_order=32,
            neetcode_category="Sliding Window",
        ),
        Problem(
            leetcode_id=76,
            title="Minimum Window Substring",
            url="https://leetcode.com/problems/minimum-window-substring/",
            difficulty="Hard",
            neetcode_order=33,
            neetcode_category="Sliding Window",
        ),
        Problem(
            leetcode_id=239,
            title="Sliding Window Maximum",
            url="https://leetcode.com/problems/sliding-window-maximum/",
            difficulty="Hard",
            neetcode_order=34,
            neetcode_category="Sliding Window",
        ),
        Problem(
            leetcode_id=206,
            title="Reverse Linked List",
            url="https://leetcode.com/problems/reverse-linked-list/",
            difficulty="Easy",
            neetcode_order=35,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=21,
            title="Merge Two Sorted Lists",
            url="https://leetcode.com/problems/merge-two-sorted-lists/",
            difficulty="Easy",
            neetcode_order=36,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=141,
            title="Linked List Cycle",
            url="https://leetcode.com/problems/linked-list-cycle/",
            difficulty="Easy",
            neetcode_order=37,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=144,
            title="Reorder List",
            url="https://leetcode.com/problems/reorder-list/",
            difficulty="Medium",
            neetcode_order=38,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=19,
            title="Remove Nth Node From End Of List",
            url="https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
            difficulty="Medium",
            neetcode_order=39,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=138,
            title="Copy List With Random Pointer",
            url="https://leetcode.com/problems/copy-list-with-random-pointer/",
            difficulty="Medium",
            neetcode_order=40,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=2,
            title="Add Two Numbers",
            url="https://leetcode.com/problems/add-two-numbers/",
            difficulty="Medium",
            neetcode_order=41,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=287,
            title="Find the Duplicate Number",
            url="https://leetcode.com/problems/find-the-duplicate-number/",
            difficulty="Medium",
            neetcode_order=42,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=146,
            title="LRU cache",
            url="https://leetcode.com/problems/lru-cache/",
            difficulty="Medium",
            neetcode_order=43,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=23,
            title="Merge K Sorted Lists",
            url="https://leetcode.com/problems/merge-k-sorted-lists/",
            difficulty="Hard",
            neetcode_order=44,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=25,
            title="Reverse Nodes in k-group",
            url="https://leetcode.com/problems/reverse-nodes-in-k-group/",
            difficulty="Hard",
            neetcode_order=45,
            neetcode_category="Linked List",
        ),
        Problem(
            leetcode_id=226,
            title="Invert Binary Tree",
            url="https://leetcode.com/problems/invert-binary-tree/",
            difficulty="Easy",
            neetcode_order=46,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=104,
            title="Maximum Depth of Binary Tree",
            url="https://leetcode.com/problems/maximum-depth-of-binary-tree/",
            difficulty="Easy",
            neetcode_order=47,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=543,
            title="Diameter of Binary Tree",
            url="https://leetcode.com/problems/diameter-of-binary-tree/",
            difficulty="Easy",
            neetcode_order=48,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=110,
            title="Balanced Binary Tree",
            url="https://leetcode.com/problems/balanced-binary-tree/",
            difficulty="Easy",
            neetcode_order=49,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=100,
            title="Same Tree",
            url="https://leetcode.com/problems/same-tree/",
            difficulty="Easy",
            neetcode_order=50,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=572,
            title="Subtree of Another Tree",
            url="https://leetcode.com/problems/subtree-of-another-tree/",
            difficulty="Easy",
            neetcode_order=51,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=235,
            title="Lowest Common Ancestor of A BST",
            url="https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
            difficulty="Medium",
            neetcode_order=52,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=102,
            title="Binary Tree Level Order Traversal",
            url="https://leetcode.com/problems/binary-tree-level-order-traversal/",
            difficulty="Medium",
            neetcode_order=53,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=199,
            title="Binary Tree Right Side View",
            url="https://leetcode.com/problems/binary-tree-right-side-view/",
            difficulty="Medium",
            neetcode_order=54,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=1448,
            title="Count Good Nodes in Binary Tree",
            url="https://leetcode.com/problems/count-good-nodes-in-binary-tree/",
            difficulty="Medium",
            neetcode_order=55,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=98,
            title="Validate BST",
            url="https://leetcode.com/problems/validate-binary-search-tree/",
            difficulty="Medium",
            neetcode_order=56,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=230,
            title="Kth Smallest Element in A BST",
            url="https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
            difficulty="Medium",
            neetcode_order=57,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=105,
            title="Construct Binary Tree from Preorder and Inorder Traversal",
            url="https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
            difficulty="Medium",
            neetcode_order=58,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=124,
            title="Binary Tree Maximum Path Sum",
            url="https://leetcode.com/problems/binary-tree-maximum-path-sum/",
            difficulty="Hard",
            neetcode_order=59,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=297,
            title="Serialize and Deserialize Binary Tree",
            url="https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
            difficulty="Hard",
            neetcode_order=60,
            neetcode_category="Tree",
        ),
        Problem(
            leetcode_id=208,
            title="Implement Trie",
            url="https://leetcode.com/problems/implement-trie-prefix-tree/",
            difficulty="Medium",
            neetcode_order=61,
            neetcode_category="Tries",
        ),
        Problem(
            leetcode_id=211,
            title="Design Add and Search Word Data Structure",
            url="https://leetcode.com/problems/design-add-and-search-words-data-structure/",
            difficulty="Medium",
            neetcode_order=62,
            neetcode_category="Tries",
        ),
        Problem(
            leetcode_id=212,
            title="Word Search II",
            url="https://leetcode.com/problems/word-search-ii/",
            difficulty="Hard",
            neetcode_order=63,
            neetcode_category="Tries",
        ),
        Problem(
            leetcode_id=703,
            title="Kth Largest Element in A Stream",
            url="https://leetcode.com/problems/kth-largest-element-in-a-stream/",
            difficulty="Easy",
            neetcode_order=64,
            neetcode_category="Heap / Priority Queue",
        ),
        Problem(
            leetcode_id=1046,
            title="Last Stone Weight",
            url="https://leetcode.com/problems/last-stone-weight/",
            difficulty="Easy",
            neetcode_order=65,
            neetcode_category="Heap / Priority Queue",
        ),
        Problem(
            leetcode_id=973,
            title="K Closest Points To Origin",
            url="https://leetcode.com/problems/k-closest-points-to-origin/",
            difficulty="Medium",
            neetcode_order=66,
            neetcode_category="Heap / Priority Queue",
        ),
        Problem(
            leetcode_id=215,
            title="Kth Largest Element in an Array",
            url="https://leetcode.com/problems/kth-largest-element-in-an-array/",
            difficulty="Medium",
            neetcode_order=67,
            neetcode_category="Heap / Priority Queue",
        ),
        Problem(
            leetcode_id=621,
            title="Task Scheduler",
            url="https://leetcode.com/problems/task-scheduler/",
            difficulty="Medium",
            neetcode_order=68,
            neetcode_category="Heap / Priority Queue",
        ),
        Problem(
            leetcode_id=355,
            title="Design Twitter",
            url="https://leetcode.com/problems/design-twitter/",
            difficulty="Medium",
            neetcode_order=69,
            neetcode_category="Heap / Priority Queue",
        ),
        Problem(
            leetcode_id=295,
            title="Find Median From Data Stream",
            url="https://leetcode.com/problems/find-median-from-data-stream/",
            difficulty="Hard",
            neetcode_order=70,
            neetcode_category="Heap / Priority Queue",
        ),
        Problem(
            leetcode_id=78,
            title="Subsets",
            url="https://leetcode.com/problems/subsets/",
            difficulty="Medium",
            neetcode_order=71,
            neetcode_category="Backtracking",
        ),
        Problem(
            leetcode_id=39,
            title="Combination Sum",
            url="https://leetcode.com/problems/combination-sum/",
            difficulty="Medium",
            neetcode_order=72,
            neetcode_category="Backtracking",
        ),
        Problem(
            leetcode_id=40,
            title="Combination Sum II",
            url="https://leetcode.com/problems/combination-sum-ii/",
            difficulty="Medium",
            neetcode_order=73,
            neetcode_category="Backtracking",
        ),
        Problem(
            leetcode_id=46,
            title="Permutations",
            url="https://leetcode.com/problems/permutations/",
            difficulty="Medium",
            neetcode_order=74,
            neetcode_category="Backtracking",
        ),
        Problem(
            leetcode_id=90,
            title="Subsets II",
            url="https://leetcode.com/problems/subsets-ii/",
            difficulty="Medium",
            neetcode_order=75,
            neetcode_category="Backtracking",
        ),
        Problem(
            leetcode_id=79,
            title="Word Search",
            url="https://leetcode.com/problems/word-search/",
            difficulty="Medium",
            neetcode_order=76,
            neetcode_category="Backtracking",
        ),
        Problem(
            leetcode_id=131,
            title="Palindrome Partitioning",
            url="https://leetcode.com/problems/palindrome-partitioning/",
            difficulty="Medium",
            neetcode_order=77,
            neetcode_category="Backtracking",
        ),
        Problem(
            leetcode_id=17,
            title="Letter Combinations of a Phone Number",
            url="https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
            difficulty="Medium",
            neetcode_order=78,
            neetcode_category="Backtracking",
        ),
        Problem(
            leetcode_id=51,
            title="N-Queens",
            url="https://leetcode.com/problems/n-queens/",
            difficulty="Hard",
            neetcode_order=79,
            neetcode_category="Backtracking",
        ),
        Problem(
            leetcode_id=57,
            title="Insert Interval",
            url="https://leetcode.com/problems/insert-interval/",
            difficulty="Medium",
            neetcode_order=80,
            neetcode_category="Intervals",
        ),
        Problem(
            leetcode_id=56,
            title="Merge Intervals",
            url="https://leetcode.com/problems/merge-intervals/",
            difficulty="Medium",
            neetcode_order=81,
            neetcode_category="Intervals",
        ),
        Problem(
            leetcode_id=435,
            title="Non Overlapping Intervals",
            url="https://leetcode.com/problems/non-overlapping-intervals/",
            difficulty="Medium",
            neetcode_order=82,
            neetcode_category="Intervals",
        ),
        Problem(
            leetcode_id=252,
            title="Meeting Rooms",
            url="https://neetcode.io/problems/meeting-schedule",
            difficulty="Easy",
            neetcode_order=83,
            neetcode_category="Intervals",
        ),
        Problem(
            leetcode_id=253,
            title="Meeting Rooms II",
            url="https://neetcode.io/problems/meeting-schedule-ii",
            difficulty="Medium",
            neetcode_order=84,
            neetcode_category="Intervals",
        ),
        Problem(
            leetcode_id=1851,
            title="Minimum interval to include each query",
            url="https://leetcode.com/problems/minimum-interval-to-include-each-query/",
            difficulty="Hard",
            neetcode_order=85,
            neetcode_category="Intervals",
        ),
        Problem(
            leetcode_id=53,
            title="Maximum Subarray",
            url="https://leetcode.com/problems/maximum-subarray/",
            difficulty="Medium",
            neetcode_order=86,
            neetcode_category="Greedy",
        ),
        Problem(
            leetcode_id=55,
            title="Jump Game",
            url="https://leetcode.com/problems/jump-game/",
            difficulty="Medium",
            neetcode_order=87,
            neetcode_category="Greedy",
        ),
        Problem(
            leetcode_id=45,
            title="Jump Game II",
            url="https://leetcode.com/problems/jump-game-ii/",
            difficulty="Medium",
            neetcode_order=88,
            neetcode_category="Greedy",
        ),
        Problem(
            leetcode_id=134,
            title="Gas Station",
            url="https://leetcode.com/problems/gas-station/",
            difficulty="Medium",
            neetcode_order=89,
            neetcode_category="Greedy",
        ),
        Problem(
            leetcode_id=846,
            title="Hand of Straights",
            url="https://leetcode.com/problems/hand-of-straights/",
            difficulty="Medium",
            neetcode_order=90,
            neetcode_category="Greedy",
        ),
        Problem(
            leetcode_id=1899,
            title="Merge Triplets to Form Target Triplet",
            url="https://leetcode.com/problems/merge-triplets-to-form-target-triplet/",
            difficulty="Medium",
            neetcode_order=91,
            neetcode_category="Greedy",
        ),
        Problem(
            leetcode_id=763,
            title="Partition Labels",
            url="https://leetcode.com/problems/partition-labels/",
            difficulty="Medium",
            neetcode_order=92,
            neetcode_category="Greedy",
        ),
        Problem(
            leetcode_id=768,
            title="Valid Parenthesis String",
            url="https://leetcode.com/problems/valid-parenthesis-string/",
            difficulty="Medium",
            neetcode_order=93,
            neetcode_category="Greedy",
        ),
        Problem(
            leetcode_id=200,
            title="Number of Islands",
            url="https://leetcode.com/problems/number-of-islands/",
            difficulty="Medium",
            neetcode_order=94,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=695,
            title="Max Area of Island",
            url="https://leetcode.com/problems/max-area-of-island/",
            difficulty="Medium",
            neetcode_order=95,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=133,
            title="Clone Graph",
            url="https://leetcode.com/problems/clone-graph/",
            difficulty="Medium",
            neetcode_order=96,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=286,
            title="Walls and Gates",
            url="https://neetcode.io/problems/islands-and-treasure",
            difficulty="Medium",
            neetcode_order=97,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=994,
            title="Rotting Oranges",
            url="https://leetcode.com/problems/rotting-oranges/",
            difficulty="Medium",
            neetcode_order=98,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=417,
            title="Pacific Atlantic Water flow",
            url="https://leetcode.com/problems/pacific-atlantic-water-flow/",
            difficulty="Medium",
            neetcode_order=99,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=130,
            title="Surrounded Regions",
            url="https://leetcode.com/problems/surrounded-regions/",
            difficulty="Medium",
            neetcode_order=100,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=207,
            title="Course Schedule",
            url="https://leetcode.com/problems/course-schedule/",
            difficulty="Medium",
            neetcode_order=101,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=210,
            title="Course Schedule II",
            url="https://leetcode.com/problems/course-schedule-ii/",
            difficulty="Medium",
            neetcode_order=102,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=261,
            title="Graph Valid Tree",
            url="https://neetcode.io/problems/valid-tree",
            difficulty="Medium",
            neetcode_order=103,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=323,
            title="Number of Connected Components in Undirected Graph",
            url="https://neetcode.io/problems/count-connected-components",
            difficulty="Medium",
            neetcode_order=104,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=684,
            title="Redundant Connection",
            url="https://leetcode.com/problems/redundant-connection/",
            difficulty="Medium",
            neetcode_order=105,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=127,
            title="Word Latter",
            url="https://leetcode.com/problems/word-ladder/",
            difficulty="Hard",
            neetcode_order=106,
            neetcode_category="Graph",
        ),
        Problem(
            leetcode_id=743,
            title="Network Delay Time",
            url="https://leetcode.com/problems/network-delay-time/",
            difficulty="Medium",
            neetcode_order=107,
            neetcode_category="Graph2",
        ),
        Problem(
            leetcode_id=332,
            title="Reconstruct Itinerary",
            url="https://leetcode.com/problems/reconstruct-itinerary/description/",
            difficulty="Hard",
            neetcode_order=108,
            neetcode_category="Graph2",
        ),
        Problem(
            leetcode_id=1584,
            title="Min Cost to Connect All Points",
            url="https://leetcode.com/problems/min-cost-to-connect-all-points/description/",
            difficulty="Medium",
            neetcode_order=109,
            neetcode_category="Graph2",
        ),
        Problem(
            leetcode_id=778,
            title="Swim in Rising Water",
            url="https://leetcode.com/problems/swim-in-rising-water/description/",
            difficulty="Hard",
            neetcode_order=110,
            neetcode_category="Graph2",
        ),
        Problem(
            leetcode_id=269,
            title="Alien Dictionary",
            url="https://neetcode.io/problems/foreign-dictionary",
            difficulty="Hard",
            neetcode_order=111,
            neetcode_category="Graph2",
        ),
        Problem(
            leetcode_id=787,
            title="Cheapest Flights in K stops",
            url="https://leetcode.com/problems/cheapest-flights-within-k-stops/description/",
            difficulty="Medium",
            neetcode_order=112,
            neetcode_category="Graph2",
        ),
        Problem(
            leetcode_id=70,
            title="Climbing Stairs",
            url="https://leetcode.com/problems/climbing-stairs/description/",
            difficulty="Easy",
            neetcode_order=113,
            neetcode_category="1DDP",
        ),
        Problem(
            leetcode_id=746,
            title="Min Cost Climbing Stairs",
            url="https://leetcode.com/problems/min-cost-climbing-stairs/description/",
            difficulty="Easy",
            neetcode_order=114,
            neetcode_category="1DDP",
        ),
        Problem(
            leetcode_id=198,
            title="House Robber",
            url="https://leetcode.com/problems/house-robber/description/",
            difficulty="Medium",
            neetcode_order=115,
            neetcode_category="1DDP",
        ),
        Problem(
            leetcode_id=213,
            title="House Robber II",
            url="https://leetcode.com/problems/house-robber-ii/description/",
            difficulty="Medium",
            neetcode_order=116,
            neetcode_category="1DDP",
        ),
        Problem(
            leetcode_id=5,
            title="Longest Palindromic Substring",
            url="https://leetcode.com/problems/longest-palindromic-substring/description/",
            difficulty="Medium",
            neetcode_order=117,
            neetcode_category="1DDP",
        ),
        Problem(
            leetcode_id=647,
            title="Palindromic Substrings",
            url="https://leetcode.com/problems/palindromic-substrings/",
            difficulty="Medium",
            neetcode_order=118,
            neetcode_category="1DDP",
        ),
        Problem(
            leetcode_id=91,
            title="Decode Ways",
            url="https://leetcode.com/problems/decode-ways/description/",
            difficulty="Medium",
            neetcode_order=119,
            neetcode_category="1DDP",
        ),
        Problem(
            leetcode_id=322,
            title="Coin Change",
            url="https://leetcode.com/problems/coin-change/description/",
            difficulty="Medium",
            neetcode_order=120,
            neetcode_category="1DDP",
        ),
        Problem(
            leetcode_id=152,
            title="Maximum Product Subarray",
            url="https://leetcode.com/problems/maximum-product-subarray/description/",
            difficulty="Medium",
            neetcode_order=121,
            neetcode_category="1DDP",
        ),
        Problem(
            leetcode_id=139,
            title="Word Break",
            url="https://leetcode.com/problems/word-break/description/",
            difficulty="Medium",
            neetcode_order=122,
            neetcode_category="1DDP",
        ),
        Problem(
            leetcode_id=300,
            title="Longest Increasing Subsequence",
            url="https://leetcode.com/problems/longest-increasing-subsequence/description/",
            difficulty="Medium",
            neetcode_order=123,
            neetcode_category="1DDP",
        ),
        Problem(
            leetcode_id=416,
            title="Partition Equal Subset Sum",
            url="https://leetcode.com/problems/partition-equal-subset-sum/description/",
            difficulty="Medium",
            neetcode_order=124,
            neetcode_category="1DDP",
        ),
        Problem(
            leetcode_id=62,
            title="Unique Paths",
            url="https://leetcode.com/problems/unique-paths/description/",
            difficulty="Medium",
            neetcode_order=125,
            neetcode_category="2DDP",
        ),
        Problem(
            leetcode_id=1143,
            title="Longest Common Subsequence",
            url="https://leetcode.com/problems/longest-common-subsequence/description/",
            difficulty="Medium",
            neetcode_order=126,
            neetcode_category="2DDP",
        ),
        Problem(
            leetcode_id=309,
            title="Best Time to Buy and Sell Stock w/ Cooldown",
            url="https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/description/",
            difficulty="Medium",
            neetcode_order=127,
            neetcode_category="2DDP",
        ),
        Problem(
            leetcode_id=518,
            title="Coin Change II",
            url="https://leetcode.com/problems/coin-change-ii/description/",
            difficulty="Medium",
            neetcode_order=128,
            neetcode_category="2DDP",
        ),
        Problem(
            leetcode_id=494,
            title="Target Sum",
            url="https://leetcode.com/problems/target-sum/description/",
            difficulty="Medium",
            neetcode_order=129,
            neetcode_category="2DDP",
        ),
        Problem(
            leetcode_id=97,
            title="Interleaving String",
            url="https://leetcode.com/problems/interleaving-string/description/",
            difficulty="Medium",
            neetcode_order=130,
            neetcode_category="2DDP",
        ),
        Problem(
            leetcode_id=329,
            title="Longest Increasing Path in a Matrix",
            url="https://leetcode.com/problems/longest-increasing-path-in-a-matrix/description/",
            difficulty="Hard",
            neetcode_order=131,
            neetcode_category="2DDP",
        ),
        Problem(
            leetcode_id=115,
            title="Distinct Subsequences",
            url="https://leetcode.com/problems/distinct-subsequences/description/",
            difficulty="Hard",
            neetcode_order=132,
            neetcode_category="2DDP",
        ),
        Problem(
            leetcode_id=72,
            title="Edit Distance",
            url="https://leetcode.com/problems/edit-distance/description/",
            difficulty="Medium",
            neetcode_order=133,
            neetcode_category="2DDP",
        ),
        Problem(
            leetcode_id=312,
            title="Burst Baloons",
            url="https://leetcode.com/problems/burst-balloons/description/",
            difficulty="Hard",
            neetcode_order=134,
            neetcode_category="2DDP",
        ),
        Problem(
            leetcode_id=10,
            title="Regex Matching",
            url="https://leetcode.com/problems/regular-expression-matching/description/",
            difficulty="Hard",
            neetcode_order=135,
            neetcode_category="2DDP",
        ),
        Problem(
            leetcode_id=136,
            title="Single Number",
            url="https://leetcode.com/problems/single-number/description/",
            difficulty="Easy",
            neetcode_order=136,
            neetcode_category="Bit Manipulation",
        ),
        Problem(
            leetcode_id=191,
            title="Number of 1 Bits",
            url="https://leetcode.com/problems/number-of-1-bits/description/",
            difficulty="Easy",
            neetcode_order=137,
            neetcode_category="Bit Manipulation",
        ),
        Problem(
            leetcode_id=338,
            title="Counting Bits",
            url="https://leetcode.com/problems/counting-bits/description/",
            difficulty="Easy",
            neetcode_order=138,
            neetcode_category="Bit Manipulation",
        ),
        Problem(
            leetcode_id=190,
            title="Reverse Bits",
            url="https://leetcode.com/problems/reverse-bits/description/",
            difficulty="Easy",
            neetcode_order=139,
            neetcode_category="Bit Manipulation",
        ),
        Problem(
            leetcode_id=268,
            title="Missing Number",
            url="https://leetcode.com/problems/missing-number/description/",
            difficulty="Easy",
            neetcode_order=140,
            neetcode_category="Bit Manipulation",
        ),
        Problem(
            leetcode_id=371,
            title="Sum of Two Integers",
            url="https://leetcode.com/problems/sum-of-two-integers/description/",
            difficulty="Medium",
            neetcode_order=141,
            neetcode_category="Bit Manipulation",
        ),
        Problem(
            leetcode_id=7,
            title="Reverse Integer",
            url="https://leetcode.com/problems/reverse-integer/description/",
            difficulty="Medium",
            neetcode_order=142,
            neetcode_category="Bit Manipulation",
        ),
        Problem(
            leetcode_id=48,
            title="Rotate Image",
            url="https://leetcode.com/problems/rotate-image/description/",
            difficulty="Medium",
            neetcode_order=142,
            neetcode_category="Math",
        ),
        Problem(
            leetcode_id=54,
            title="Spiral Matrix",
            url="https://leetcode.com/problems/spiral-matrix/description/",
            difficulty="Medium",
            neetcode_order=143,
            neetcode_category="Math",
        ),
        Problem(
            leetcode_id=73,
            title="Set Matrix Zeroes",
            url="https://leetcode.com/problems/set-matrix-zeroes/description/",
            difficulty="Medium",
            neetcode_order=144,
            neetcode_category="Math",
        ),
        Problem(
            leetcode_id=202,
            title="Happy Number",
            url="https://leetcode.com/problems/happy-number/description/",
            difficulty="Easy",
            neetcode_order=145,
            neetcode_category="Math",
        ),
        Problem(
            leetcode_id=66,
            title="Plus One",
            url="https://leetcode.com/problems/plus-one/description/",
            difficulty="Easy",
            neetcode_order=146,
            neetcode_category="Math",
        ),
        Problem(
            leetcode_id=50,
            title="Pow x, n",
            url="https://leetcode.com/problems/powx-n/description/",
            difficulty="Medium",
            neetcode_order=147,
            neetcode_category="Math",
        ),
        Problem(
            leetcode_id=43,
            title="Multiply Strings",
            url="https://leetcode.com/problems/multiply-strings/description/",
            difficulty="Medium",
            neetcode_order=148,
            neetcode_category="Math",
        ),
        Problem(
            leetcode_id=2103,
            title="Detect Squares",
            url="https://leetcode.com/problems/detect-squares/description/",
            difficulty="Medium",
            neetcode_order=149,
            neetcode_category="Math",
        ),
    ]
    with Session(engine) as session:
        statement = select(Problem)
        results = session.exec(statement)
        if results.first():
            print("DB already init")
            return
        for problem in problems_data:
            session.add(problem)
        session.commit()
